<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Assets\AppIcon.ico</ApplicationIcon>
    <LangVersion>13.0</LangVersion>
    <RootNamespace>AaronOS_App</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\AppIcon.ico" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <PackageReference Include="WPF-UI" Version="4.3.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\AaronOS.Core\AaronOS.Core.csproj" />
    <ProjectReference Include="..\AaronOS.Modules.BodyMeasurements\AaronOS.Modules.BodyMeasurements.csproj" />
    <ProjectReference Include="..\AaronOS.Modules.Finance\AaronOS.Modules.Finance.csproj" />
    <ProjectReference Include="..\AaronOS.Modules.Nutrition\AaronOS.Modules.Nutrition.csproj" />
    <ProjectReference Include="..\AaronOS.Modules.Medical\AaronOS.Modules.Medical.csproj" />
    <ProjectReference Include="..\AaronOS.Modules.Schedule\AaronOS.Modules.Schedule.csproj" />
  </ItemGroup>
</Project>
